Review
tavisca-cpadole/Review_cart pull request #1
Opened 2019-08-06 06:48 UTC by tavisca-cpadole

2019-08-06 07:24 UTC, tavisca-mswarnesh commented on AddToCart/Program.cs
> +        public double GetFinal()
please use appropriate name

2019-08-06 07:24 UTC, tavisca-mswarnesh commented on AddToCart/Program.cs
> +        public Double GetPrice(Product product)
Double is also fine but i think it is unnecessary boxing

2019-08-08 07:47 UTC, KumarWaghmode requested changes

2019-08-08 07:47 UTC, KumarWaghmode commented on AddToCart/Program.cs
> +    public class Product {
This class should be in different file

2019-08-08 07:47 UTC, KumarWaghmode commented on AddToCart/Program.cs
> +                throw new EmptyCartException();
Wrong exception

2019-08-08 07:47 UTC, KumarWaghmode commented on AddToCart/Program.cs
> +    public class Discount {
Move this class in different file

2019-08-08 07:47 UTC, KumarWaghmode commented on AddToCart/Program.cs
> +    public enum Category
Move this class in different file

2019-08-08 07:47 UTC, KumarWaghmode commented on AddToCart/Cart.cs
> +        public bool DiscountApplied { get; set; } = false;
Why is this public property??

2019-08-08 07:47 UTC, KumarWaghmode commented on AddToCart/CartItem.cs
> +                throw new EmptyCartException();
This is wrong exception

2019-08-08 07:47 UTC, KumarWaghmode commented on AddToCart/CategoryDiscount.cs
> +        public void UpdateDiscount(string category, double updatedDiscount)
What is use case of this method??

2019-08-08 07:47 UTC, KumarWaghmode commented on AddToCart/CategoryList.cs
> +        grocery,
Enum value should be Pascal

2019-08-08 08:29 UTC, closed without merging